import NavBar from "@/components/NavBar/navBar";
import { Rubik } from "next/font/google";
import "@/styles/global.scss";

const inter = Rubik({
  weight: ["400", "500"],
  subsets: ["latin-ext"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html className={inter.className}>
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
